version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload:
          file: /target/site/jacoco/jacoco.xml

  docs:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build-docs
          command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs

      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs

workflows:
  sample:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - docs:
          requires:
            - test
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - test
            - docs
          filters:
            branches:
              only: master

build-deploy:
  jobs:
    - build:
        filters:
          branches:
            only:
            - master

  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'